Adds a failing test case for jsdoc http://codereview.appspot.com/4905041
Distilled test case which causes jsdoc rewriter to fail with a runtime exception.
com.google.caja.SomethingWidgyHappenedError: Error calling ctor public com.google.caja.parser.js.ValueProperty(com.google.caja.lexer.FilePosition,java.lang.Void,java.util.List) with value = null () with children = [SpecialOperation : FUNCTION_CALL, NullLiteral : null] (class java.util.ArrayList)
	at com.google.caja.parser.ParseTreeNodes.newNodeInstance(ParseTreeNodes.java:62)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.rewrite(JsdocRewriter.java:168)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.rewriteAll(JsdocRewriter.java:480)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.documentExpression(JsdocRewriter.java:238)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.documentObjectConstructor(JsdocRewriter.java:399)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.rewrite(JsdocRewriter.java:154)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.documentDeclaration(JsdocRewriter.java:284)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.rewrite(JsdocRewriter.java:152)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.rewriteAll(JsdocRewriter.java:480)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.delayDocingOfUninitializedVariables(JsdocRewriter.java:466)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.rewrite(JsdocRewriter.java:166)
	at com.google.caja.ancillary.jsdoc.JsdocRewriter.rewriteFile(JsdocRewriter.java:89)
	at com.google.caja.ancillary.jsdoc.Jsdoc.sourceCodeWithDocHooks(Jsdoc.java:145)
	at com.google.caja.ancillary.jsdoc.Jsdoc.extract(Jsdoc.java:88)
	at com.google.caja.ancillary.jsdoc.JsdocTest.assertExtracted(JsdocTest.java:863)
	at com.google.caja.ancillary.jsdoc.JsdocTest.testSpecialOperation(JsdocTest.java:719)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at com.google.caja.util.CajaTestCase.runTest(CajaTestCase.java:498)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.google.caja.parser.ParseTreeNodes.newNodeInstance(ParseTreeNodes.java:54)
	... 35 more
Caused by: java.lang.ClassCastException: com.google.caja.parser.js.SpecialOperation cannot be cast to com.google.caja.parser.js.StringLiteral
	at com.google.caja.parser.js.ValueProperty.<init>(ValueProperty.java:35)
	... 40 more

R=mikesamuel@gmail.com


git-svn-id: http://google-caja.googlecode.com/svn/trunk@4591 360991c0-9f3b-0410-ba87-8b362a00edf4